server:
  port: 8082

spring:

  application:
    name: deal-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:dealdb}
    username: ${DB_USERNAME:appuser}
    password: ${DB_PASSWORD:apppass}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml
    liquibase-schema: deal_service
    default-schema: deal_service
    user: ${DB_USERNAME:appuser}
    password: ${DB_PASSWORD:apppass}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:dealdb}
    driver-class-name: org.postgresql.Driver


  jackson:
    property-naming-strategy: SNAKE_CASE

logging:
  level:
    root: INFO