server:
  port: 8081

spring:

  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:appdb}
    username: ${DB_USERNAME:appuser}
    password: ${DB_PASSWORD:apppass}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml
    liquibase-schema: user_service
    default-schema: user_service
    user: ${DB_USERNAME:appuser}
    password: ${DB_PASSWORD:apppass}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:appdb}
    driver-class-name: org.postgresql.Driver

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/appdb
    username: appuser
    password: apppass


  jackson:
    property-naming-strategy: SNAKE_CASE

logging:
  level:
    root: INFO